/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.*;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    //-----------------roll method------------------------------
    public static int[] roll(int n){
        int[] rollsValues = new int[n];
        Random randomNum = new Random();
        for (int i=0; i < rollsValues.length; i++){
            rollsValues[i]=randomNum.nextInt(6)+1;
        }

        return rollsValues;
    }


    //-----------------containsDuplicates method------------------------------
    public  static  boolean containsDuplicates (int[] arr){
        for (int i = 0; i < arr.length; i++) {
            for (int j = i+1; j< arr.length; j++) {
                if (arr[i]== arr[j]){
                    return true;
                }
            }
        }
        return false;

    }

    //-----------------calculatingAverages mathod------------------------------

    public static double calculatingAverages(int[] arr){
        double arrayValuesSummation = 0.0;
        double average = 0.0;
        for (int number : arr){
            arrayValuesSummation = arrayValuesSummation + number;

        }
        average = arrayValuesSummation / arr.length;
        return average;
    }


    //-----------------lowestAverage method------------------------------

    public static int[] lowestAverage(int[][] arr){
        double summation=0.0;
        double lowestAvg=0.0;
        double avg=0.0;
        int[] lowestAvgArray=null;
        for(int[] itemArr : arr ){
            summation=0.0;
            avg=0.0;
            for(int item : itemArr ){
                summation = summation + item;

            }
            avg = summation/itemArr.length;
            if (lowestAvg==0.0){
                lowestAvg=avg;

            }else if (avg <lowestAvg){
                lowestAvgArray= itemArr ;

                lowestAvg =avg;

            }
        }
        return lowestAvgArray;
    }
}
