/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.IOException;
import java.nio.file.*;

import java.util.List;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String path = "C:\\Users\\STUDENT\\401courseJAVA\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js";
        String ifError=  checkJSfile(path);
        System.out.println(ifError);
//        System.out.println(new App().getGreeting());
    }

    public static String checkJSfile(String link) {
        int lineCounter=0;
        String err = "";
        Path path= Paths.get(link);
        try{
            List<String> lines= Files.readAllLines(path);
            if(lines.size()!=0){
                for (String line : lines){
                    lineCounter++;
                    if(!(line.isBlank() || line.endsWith("}") || line.endsWith("{")|| line.endsWith(";") || line.contains("if") || line.contains("else"))){
                        err =err + "Line "+ lineCounter +" : Missing semicolon.\n";
                    }
                }
            }else return "Empty File.";
        }catch (IOException exception){
            exception.printStackTrace();
        }
        return err;
    }


}
