/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void restsToString() {
        Restaurant rest = new Restaurant("MAC","30");
        String str = rest.toString();
        assertEquals(str, rest.toString(), "Restaurant's reviews should be printed");
    }

    @Test
    void reviewToString(){
        Review review =new Review("very good","hasan",4);
        String str = review.toString();
        assertEquals(str, review.toString(),"Reviews of the users should be printed");
    }

    @Test
    void association(){
        Restaurant rest = new Restaurant("MAC", "30");
        Review rev = new Review("tasty","zaater",5);
        rest.addReview(rev);
        String str1 = rest.toString();
        String str2 = rev.toString();
        assertTrue(str1.contains(str2),"Restaurant's reviews should be the same as the Reviews of the users ");
    }
}
